studentquiz/moodle-mod_studentquiz

reportlib.php

Neither the statistics or the ranking report would work with MS SQL Server. It was giving an error about fields not being in the group by clause. I have added those fields and tested against MS SQL Server, Postgresql and MySQL.

Added values to group by clauses that was causing an MS SQLServer error

---

classes/question/bank/performances_column.php
classes/question/bank/tag_column.php

In StudentQuiz v3.0.1 (2018011100) it was found that after you add a question to the quiz, it would take several minutes or longer to load the view page.
This was due to ineffective database queries when gathering the tag and question attempt stats to be displayed on the screen in the question summary table.
Both processes for gather tags and question attempt stats have improved so it can be loaded under a second.

Performance: Optimise loading time of quiz questions.

---

classes/task/delete_quiz_after_migration.php

This issue causes the scheduled task to fail on any site that uses something other than mdl_ for $CFG->prefix (including behat tests that cause the task to run if $CFG->behat_prefix is something else).

Remove mdl_prefixes from table names. Fixes #28

---

classes/question/bank/difficulty_level_column.php
classes/question/bank/question_name_column.php
classes/question/bank/rate_column.php
classes/question/bank/studentquiz_bank_view.php
renderer.php
view.php

Support dynamic config to show/hide specific columns
Support custom tooltips for Difficulty and Rate columns sorting
Added Question name column to allow better customization
Convert some function to public for better override
P/S: Explain for Support custom tooltips for Difficulty and Rate columns sorting:
Column base support custom title and tooltip but there is a bug related to it but there is a but related to it.
I already create a Bug on Moodle Tracker to fix this
https://tracker.moodle.org/browse/MDL-62814
After this was fixed, StudentQuiz sorting can use a custom title and tooltip (previously the title and tooltip is the same)

Enhancement for Question Table Columns

---

lang/en/studentquiz.php
mod_form.php
settings.php
tests/behat/admin_settings.feature

Hi Frank,
We have an enhancement for StudentQuiz as below:
-----------------------------------
We are likely to recommend only specific ‘simple’ question types are used in Student Quiz activities
Currently, each time a new activity is set up, it defaults to all questions types.
We would prefer that the server settings for the Student Quiz plugin (/admin/settings.php?section=modsettingstudentquiz) allowed administrators to set the defaults.
Currently, there is a hidden setting that defaults to “Allow all question types”.
So an alternative option should be available to set specific defaults, as shown in Figure 1.
If specific question types are selected, they should be inherited every time a new Student Quiz activity is created on the server.
Note that those creating the activity are still …

Enhancement: Setting default question types at server-level

---

attempt.php
classes/question/bank/question_bank_filter.php
classes/question/bank/studentquiz_bank_view.php
db/uninstall.php
db/upgrade.php
index.php
migrate.php
preview.php
questionbank.ajax.php
renderer.php
reportrank.php
reportstat.php
view.php

From [MDL-62822](https://tracker.moodle.org/browse/MDL-62822?focusedCommentId=647722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-647722)
> **attempt.php**
> 1. Any reason for including config.php this way?
>   - My suggestion is to replace that and other occurrences by:
> `require_once(__DIR__ . '/../../config.php');`
> 2. Usually we avoid this can we replace that to use html_writter instead?

fixed import coding style and use html_writer whenever html tags need to be written

---

comment_list.php
locallib.php
remove.php
save.php

From [MDL-62822](https://tracker.moodle.org/browse/MDL-62822?focusedCommentId=647722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-647722)
> save.php
In my opinion these functions mod_studentquiz_save_rate() and mod_studentquiz_save_comment() should be moved to lib.php or locallib.php. The current placement doesn't seem right to me.
- also created a function (and moved the code to it) to remove a comment, honoring the present rules

moved functions used inline in ajax files into locallib

---

index.php
locallib.php
reportrank.php
reportstat.php
view.php

From [MDL-62822](https://tracker.moodle.org/browse/MDL-62822?focusedCommentId=647722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-647722)
> index.php
Usually the event trigger should be placed AFTER the content is rendered, so this event trigger should be moved BELOW the line 107 in that file.
Same thing happens in other files, please place all event trigger calls after the content is actually rendered.

Trigger events after output has been sent

---

db/upgrade.php
version.php

Hi Frank,
The XMLDB "Check defaults" tool was run via /admin/tool/xmldb/.
The following inconsistencies were found in mod_studentquiz:
Table: studentquiz_progress. Field: lastanswercorrect, Expected - Actual '0'
Table: studentquiz_progress. Field: attempts, Expected - Actual '0'
Table: studentquiz_progress. Field: correctattempts, Expected - Actual '0'
The upgarde.php has been modified to match install.xml.
Many thanks,
Mahmoud

Student Quiz: Inconsistent database defaults

---

styles.css

Hi Frank, 
I have a small change as below:
As can be seen in the attached screenshots (Firefox, normal 100% zoom), there's no padding between the 'Timing information' banner and any other content, including the bottom of the StudentQuiz activity area.
We should add padding to the bottom of the same size as between the button and the top of the 'Timing information' banner as shown in screenshot 1 (attached)
Thanks,
Huong Nguyen

StudentQuiz: 'Timing Information' banner needs a little padding along the bottom

---

classes/question/bank/studentquiz_bank_view.php

Hi Frank,
I have a small change as below:
If question-creating phase is yet to start, hide the green "There are no questions in this StudentQuiz. Feel free to add some questions" label
as you can't add any questions

StudentQuiz: Question-writing and Question-responding phase

---

lang/en/studentquiz.php

Thanks!
That would provide such a link:

Provide a 'More help' link to MoodleDocs in activity chooser.

---

attempt.php
renderer.php
styles.css

You can now enforce Rating and Commenting (or not).
However, you only find out if it is enforced if you try saving/moving on without having rated or commented.
So the easiest thing is to be consistent with other required fields in Moodle and apply the image of the red asterisk (e.g. the "Title" field in the SQ instance set-up page).
Expected:
Thanks,

When Rating/Comment enforced, visual cue

---

docs/teacher/reuse.rst

Helps #207 , while https://github.com/frankkoch/moodle-mod_studentquiz/blame/4ecc44112e0455ae7539eedd6acf6b7936d6565d/docs/teacher/reuse.rst#L16 already describes that the questions are part of the activity category, it is not known that having questions in a category of the activity will duplicate as well when you duplicate the activity.
Is this the best place to describe that?

clarify duplication of questions due to activity instance category

---

lang/en/studentquiz.php
mod_form.php
settings.php

Currently, the help text always said that the default value is 10 minutes, even the default setting was changed in the Admin setting

Incorrect comment deletion period helptext

---

backup/moodle2/backup_studentquiz_stepslib.php
backup/moodle2/restore_studentquiz_stepslib.php
classes/event/studentquiz_digest_changed.php
classes/observer.php
classes/task/send_digest_notification_task.php
classes/task/send_no_digest_notification_task.php
classes/utils.php
db/access.php
db/events.php
db/install.xml
db/messages.php
db/tasks.php
db/upgrade.php
lang/en/studentquiz.php
lib.php
locallib.php
mod_form.php
templates/digest_email_notification.mustache
templates/single_email_notification.mustache
tests/cron_test.php
version.php

Hi @frankkoch,
I have a enhancement as below:
---------------------------------------------------
Currently in StudentQuiz, you can add students/tutors to the Notification permissions, and they will receive an email every time a question is approved/deleted/edited. 
We might want to start using this feature at some point, but currently these settings could lead to some poor tutors receiving hundreds of emails.
So in forums (specifically, our ForumNG), we have settings that sends a single 'daily summary' (for days where there is at >1 action). This means that on busy days, our users receive a single summary email, than notifications for each individual action.
I believe that there is also a weekly as well as daily summary option.
So strategically, it would be good to implement a similar …

StudentQuiz: Notification control (daily/weekly digest email settings)

---

attempt.php
lang/en/studentquiz.php

Hi Frank,
Currently when you take a quiz in StudentQuiz, there is no further 'level' in the crumbtrail beyond the activity's 'main' page:
The feedback is essentially that this looks 'odd', and it would be expected that "Question [1|2] of 2" would be the logical 'level' in the crumbtrail.
Clicking on the activity name ("Example studentquiz (publish automatically" in the above) should continue taking you back to the 'main' page.
Thanks,

Add crumbtrail when taking quizzes

---

templates/comment.mustache

Keep the default margin of the *p* tag

The deleted text/Comment text is shifting when click on Expand/Collapse icon

---

locallib.php

See https://github.com/frankkoch/moodle-mod_studentquiz/issues/284#issuecomment-732348655

fix #284: exclude hidden questions as candidate in the rating part of the ranking calculation

---

attempt.php
classes/access/context_override.php
classes/observer.php
commenthistory.php
db/caches.php
db/events.php
db/upgrade.php
lang/en/studentquiz.php
locallib.php
preview.php
reportlib.php
tests/permissions_test.php
version.php

Before this comment, as soon as any role was changed, the permissions for
all student-quizzes were changed.
After this, when the roles change, then we note that time in a cache.
Then, when a user tries to access a StudentQuiz, if the roles have
changed since we last synced permissions for this StudentQuiz,
then we re-sync them (and note the fact in the cache).
Because of the way the cache is used, if the caches are purged, then
we will re-sync the permissions for each StudentQuiz the next time a
user tries to access it.

Improve role sync performance. Fixes #306

---

lang/en/studentquiz.php
tests/behat/preview_question.feature

Hi Frank,
If you use 'View as Student' to preview a question, "available" is misspelled. I have fixed the typo. Could you please help me to review it?
Thanks.

The lang string is misspelled

---

classes/commentarea/container.php
tests/behat/add_studentquiz.feature
tests/behat/admin_settings.feature
tests/behat/aggregated_changes_import.feature
tests/behat/anonymised_instance.feature
tests/behat/behat_mod_studentquiz.php
tests/behat/changes_restorable.feature
tests/behat/comment_area_create.feature
tests/behat/installed.feature
tests/behat/moodle_backup.feature
tests/behat/navigation.feature
tests/behat/preview_question.feature
tests/behat/question_submission_answering_phases.feature
tests/behat/run_quiz.feature
tests/behat/startpageview.feature
tests/behat/state_visibility.feature
tests/behat/state_visibility_old_backup_import.feature

The summary of my working:
1. I tried to remove as much as possible the @javascript tag
2. I tried to correct the 'Give' 'When' 'Then' statement in each scenario
3. I defined the step: I am on the "]StudentQuizName]" "mod_studentquiz > [Pagetype]" page for student quiz
4. I have fixed the deprecated function get_all_user_name_fields() 
5. I tried to remove duplicated code to move them to the Background if it is possible
6. The step "I add a "activity" to section "sectionnumber" and I fill the form with:" has been changed recently. It need @javascript tag to run.
In the near future, I will continue to improve the behat tests for comments. There are many "waiting" step that shouldn't include into the test case, but the js implement is not working correctly (The js_pending isn't used in all …

StudentQuiz: Behat tests could be improved

---

backup/moodle2/backup_studentquiz_stepslib.php

We are missing annotation for userid and questionid. If we backup an studentquiz and restore, then we preview the question and view the state history, sometime it will throw an error

Add anotate_ids for statehistory backup stebslib

---

lang/en/studentquiz.php
renderer.php
tests/behat/question_submission_answering_phases.feature
view.php

In this commit, I have fix some issues:
1. Disable all action buttons when no questions are selected.
2. In case people cheat by typing directly in the url, I have added the code to redirect after remove the action from the parameters if:
- We enter the change sate confirmation screen or delete confirmation screen without any selected question.
- We move to category without any selected question
3. In the behat tests, I have added @javascript to make sure the js code to click on the "check all" button will be called before we check the disable attribute of buttons.
Hi @timhunt,
could you please help me to review it?
Thanks.

Disable buttons when there are no selected questions

---

renderer.php

We use a pipe ( | ) divider in "My attempts" to differentiate between the two data, so we should possibly do the same for "Comments".

Fix inconsistency division in columns

---

classes/condition/studentquiz_condition.php
classes/question/bank/studentquiz_bank_view.php

Step to reproduce the bug:
1. Go to the SQ with atleast 1 question.
2. Open the filter, click on "show more ..."
3. Enter a number in the 'comment' and click filter
Actual result:
A database error screen will appear:
_Debug info: ERROR: missing FROM-clause entry for table "co"
LINE 45: ...R (dl.difficultylevel IS NULL AND 0 > $6))) AND ((co.comment..._
When we developed the private commenting function, we have modified the comment column and changed the table alias. I updated the table name of the filter in this commit to match with the change in comment column (as default the filter will be base on the public comment)
Hi @timhunt, could you please help me to review this pull request?

Fix bug adding filter to 'comment' throws error

---

classes/question/bank/studentquiz_bank_view.php

I have fixed a coding notice in this commit
Step to reproduce:
Step 1: Login as an admin, turn on the _Display debug message_ option in the /admin/settings.php?section=debugging
Step 2: Turn editing 'ON' , add student quiz activity
Step 3: Add questions to Student quiz activity (You can add question either as student/admin/tutor)
Step 4: click on 'Start quiz' to attempt the quiz
After the completion of attempt , click on the following links (T-type , S -sort ,Question, Action , Tag ,My attempt, Difficulty ,Rating ,Comments)
Actual Result : Getting the following error on the top of the page 
Notice: Trying to get property 'privatecommenting' of non-object in /var/www/html/moodle/mod/studentquiz/classes/question/bank/studentquiz_bank_view.php on line 947
In some cases, the construct …

Fix 'privatecommenting' of non-object errors

---

renderer.php
tests/behat/state_visibility.feature
view.php

Hi @timhunt,
In this commit, I have fixed some UI to improve UX.
When the tutor does not have 'changestate' permission set. The page throw error as the image below:
I have listed cases I have changed when the tutor does not have 'changestate' permission
1. 'Change state' button will be hidden  in the studentquiz view
2. The icon in state column will be disabled
3. To ensure security, when we copy the URL change state of questions from browser A to another browser, 
I have displayed a warning message.
I have also updated behat test for this case.
Could you please help me to review it?
Many thanks.

Display error page when Tutor does have 'change state' capability

---

classes/condition/studentquiz_condition.php
tests/behat/startpageview.feature

I have fixed the bug throwing error when filter by 'Difficult for me' option
Step to reproduce:
Step 1: Login as an admin, Navigate to any course 
Step 2: Turn editing 'ON' , add student quiz activity
Step 3: Add questions to Student quiz activity
Step 4: click on 'Start quiz' to attempt the quiz
Step 5: After the completion of attempt , click on the "Difficult for me" button  and click on Filter -> got "Error reading from DB" error.
Debug info: ERROR: division by zero
The filter (fast filter and advance filter) do not have automation test to reduce the obvious bugs like this bug. I've added a Behat test for the fast filter first in this commit. Some other bugs with the filter options in 'show more...' are fixing by our developers, and I will ask them to update a Behat test for them.
Hi …

Fix bug when filter by 'Difficult for me' option

---

classes/question/bank/question_bank_filter.php
classes/question/bank/studentquiz_bank_view.php
styles.css
tests/behat/filter.feature

Hi Tim, 
In this commit, I have fixed errors in the filter of the Studentquiz as the image below:
I. I have update the new form validation in client side:
II. I have also fixed some bugs relating to the filter:
1. Enable Creation date is after/is before throws error
- At creation we check enable date is after/is before then click on 'Filter' button. The filter can be run without errors message
2. Fix validation message display in the responsive UI. 
III. The git action errors are not correct:
1. The function names use to override methods from the base class, so I can not update their names.
2. Do not require phpdoc for methods that override base class.
Could you please help me review it?
Many thanks, Tim

Fix filter errors and add behat in the advance filter

---

styles.css

Hi Tim,
I have created the commit to change the approach CSS in form-group filter.
As I have discussed with you, we have no choices in the situation so I have set CSS important but it makes the cibot warning. I think we ignore the cibot warning in this case.
Could you please help me to review it?
Thanks

Studentquiz: Update css for displaying error form-group

---

attempt.php
classes/question/bank/question_bank_filter.php
classes/question/bank/studentquiz_bank_view.php
renderer.php
tests/behat/pagination.feature
view.php
viewlib.php

Hi Tim,
I have used the base_url to make all the actions in StudentQuiz question bank view have consistent behavior.
Most of logic is handle the base_url is in load_questionbank function.
Also, I have removed some the unused param like get_filtered_question_ids.
I have added changepagesize input because when we have an url like with query params like  cmid=1&qperpage=25 and don't have sesskey, it will cause an error.
Could you please take a look at this approach and peer-review it.
Man thanks

StudentQuiz: page size setting is forgotten if you edit a question

---

lib.php

Hi @timhunt ,
Look like I make a mistake when I fix code checker error(change or to ||).
|| does not allow to using the same variable for two side but OR allow it.
Could you please help me to review the changes?
Many thanks

Fix incorrect syntax error

---

classes/question/bank/studentquiz_bank_view.php
renderer.php

Hi @timhunt ,
When I try this the defect related to this 619311 on our OSEP theme.
I found out we can't style the warning message directly since they really don't have a wrapper div. We can't style it without affecting other elements.
So I add a wrapper and move it to the renderer so we can easily customize it.
Does it make sense?

Create new renderer function for warning message

---

lib.php

Hi,
On Moodle 3.9, added images work normally when we add them in text editor and when we preview them.
However, when we start quiz, they do not appear.
This is fixed in main branch (https://github.com/studentquiz/moodle-mod_studentquiz/commit/7af298d82a5dd3d487caed80c50039f29e5b5662), but can it be fixed in 3.x branche too ?

Broken images when quiz is launched

---

classes/local/studentquiz_question.php
locallib.php
tests/locallib_test.php

Hi @timhunt ,
I have fixed the issue to make sure we only send to the tutors in the group that students belong to.
I add some unit tests as well.
Note: the unit test failed is not related to this issue, It will be fixed in ticket 683232

StudentQuiz: Tutor digest notification not respecting tutor groups

---

classes/local/external/get_comments_api.php

Hi @timhunt ,
This change is to fix the wrong declaration of sort param that causing the warning in 724262
So this issue is ready for review

StudentQuiz: Fix wrong param declaration

---

classes/statistics_calculator.php

Without this, the many sub-queries in stats calculations that JOIN the question_references table dont hit any of the indexes on that table. For sites with large question_references tables - this can be horrible for performance as it ends up doing a seqscan on that table.
By adding the usingcontextid field, we instead get indexscan's.

Improve performance of statistics queries

---

attempt.php
changestate.php
classes/completion/custom_completion.php
classes/local/studentquiz_question.php
classes/utils.php
commenthistory.php
hideaction.php
pinaction.php
preview.php
reportlib.php
reportrank.php
reportstat.php
save.php
tests/backup_test.php
tests/bank_performance_test.php
tests/bank_view_test.php
tests/report_test.php
tests/viewlib_test.php
view.php
viewlib.php

Refactor the authentication code

StudentQuiz: ERROR: missing param "userid" in query when logging in with StudentQuiz link

---

classes/privacy/provider.php

It was observed, that deleting users took a very long time. The observed time ranges were 5-14 hours. The problem was brought to our attention because it caused other adhoc task to pile up behind it.
Checking the mysql processlist consistently showed the same queries and these could be tracked down into the mod_studentquiz dataprivacy integration.
Running the SQLs manually against our staging system with a mostly idleing MariaDB showed the same behavior (the manual tests were interrupted after 1/2 hour).
To give an insight into the order of magnitude of our DB, here are the  numbers for the affected tables:
| Table                              | Rowcount |
|------------------------------------|----------|
|mdl_context                         |   1726200|
|mdl_studentquiz …

Performance problem deleting users from moodle system
