.travis.yml
backup/moodle2/backup_studentquiz_stepslib.php
backup/moodle2/restore_studentquiz_stepslib.php
classes/question/bank/difficulty_level_column.php
classes/question/bank/question_bank_filter.php
classes/question/bank/question_text_row.php
classes/question/bank/tag_column.php
classes/question/bank/vote_column.php
db/install.php
db/uninstall.php
import_form.php
styles.css
version.php
viewlib.php

Changes include:
* Adjusting code to fix reported errors & warnings

New version v1.0.9.

---

db/upgrade.php
reportlib.php

Fixing transact sql

---

lib.php

This pull request is to fix issue #29.

Implement mod_studentquiz_question_pluginfile for question images.

---

locallib.php
renderer.php

Upon seeing this <img width="1230" alt="studentquiz-buttonclasses" src="https://user-images.githubusercontent.com/377279/39521386-97f3092a-4e0e-11e8-8b59-82520fd92245.png">
I thought it might be a good idea to add bootstrap classes here and there.
This patch does not claim to have spotted all places this might apply!

Added bootstrap classes to three button and a textarea.

---

classes/question/bank/anonym_creator_name_column.php
classes/question/bank/approved_column.php
classes/question/bank/comments_column.php
classes/question/bank/difficulty_level_column.php
classes/question/bank/performances_column.php
classes/question/bank/rate_column.php
classes/question/bank/tag_column.php
lang/en/studentquiz.php
renderer.php

Hi Frank,
As previous conversation. I'm going to make Pull Request for phase 1 "Move columns display content to render" for that allow theme to override the content and styling for columns content
Huong Nguyen

Move columns display content to render

---

classes/question/bank/studentquiz_bank_view.php
renderer.php
styles.css
view.php

Move display parts to Renderer
Move fake blocks to Renderer to support custom region

Enhancement for Question Table

---

classes/privacy/provider.php
lang/en/studentquiz.php
tests/privacy_test.php

Hi Frank,
I have implemented the GDPR for StudentQuiz plugin, could you please help me to review it? and I've also attached an example of how exported data will look like.
[export.zip](https://github.com/frankkoch/moodle-mod_studentquiz/files/2183273/export.zip)
Many thanks,
Kiet

Implement GDPR

---

view.php

From [MDL-62822](https://tracker.moodle.org/browse/MDL-62822?focusedCommentId=647722&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-647722)
> view.php
Some of those checks can be removed, since few lines below in view.php it creates a new instance of mod_studentquiz_report and the constructor of that class does same checks.

remove duplicate checks

---

pix/star.svg
pix/star_empty.svg
pix/star_empty_icon.svg
pix/star_icon.svg

If you like, use those SVG star icons I made.
Best,
Luca

Adding SVG star icons.

---

classes/question/bank/studentquiz_bank_view.php
renderer.php
tests/behat/run_quiz.feature
tests/studentquiz_bank_view_test.php
view.php

Variant to reintroduce GET params for the view page to allow filtering and other setting options of the page to be used together. attempts to address https://github.com/frankkoch/moodle-mod_studentquiz/issues/105

View all in get

---

db/upgrade.php
version.php

successor of https://github.com/frankkoch/moodle-mod_studentquiz/pull/115

Mkassaei xmldb default studentquiz progress

---

lang/en/studentquiz.php

Fix missing notification language string

---

classes/question/bank/question_bank_filter.php
classes/question/bank/studentquiz_bank_view.php
lang/en/studentquiz.php

Accessibility: Filtering screenreadability

---

lang/en/studentquiz.php
locallib.php

When in Anonymous mode, if you have email notifications switched on, the emails still tell you usernames

---

classes/question/bank/difficulty_level_column.php

Difficulty bar not work with PosgreSQL Database

---

classes/observer.php
db/events.php
renderer.php
version.php

Hi Frank,
Please help me to review it.
This will resolve #165 
Also, in this branch:
- Use core_user::get_user() instead of user_get_users_by_id (For better performance)
- Created code to handle if the question created User does not exist in the System
Thanks,
Huong Nguyen

Fixing bug related to Question moving

---

locallib.php
tests/viewlib_test.php

Thanks @timhunt for the comment,
I already fixed the code and created Unit Test for this case
This will resolve #182 
Thanks,

Improve auto set-up of question capabilities when a StudentQuiz is created

---

db/upgrade.php
version.php

cc @lamtranb @HuongNV13 'modified' column didn't exist and I didn't catch that https://github.com/frankkoch/moodle-mod_studentquiz/pull/191/files#diff-c74097fbb0a2db56a0a98aaf7d6a2654R564

Fix 410 upgrade

---

lang/en/studentquiz.php
templates/comment.mustache

Hi all,
When hover over the 'Report' button.
Hover text simply says "Report".
Could we please tweak our hover text to say "Report comment as unacceptable".
Please help me review it.
Thanks.

StudentQuiz/Comments: Report hovertext tweak

---

classes/utils.php

Hi all,
There is a bug in error handler when user sent to email report.
Please help me review.
Thanks.

StudentQuiz\Comments: Display error when user sent to email report

---

lib.php
tests/behat/add_studentquiz.feature
tests/studentquiz_add_test.php

Hi all, 
Please help me review it.
Many thanks

StudentQuiz/Comment :  Can't save Comment deletion period (minutes) is 0 when create StudentQuiz

---

classes/question/bank/sq_hidden_column.php
classes/question/bank/studentquiz_bank_view.php

Fixes #201 
Fixes also issues with navigation because of that (empty question page).
@HuongNV13 can you review the changes please? You provided that code part initially
Review Notes:
- Changed the "LEFT JOIN" to a "JOIN", so it now limits the Resultset
- That's why most other parts could be omitted so I removed them as well

Exclude hidden questions in question resultset if the user is not allowed to view them, instead of just not showing them.

---

classes/condition/studentquiz_condition.php
classes/local/db.php
classes/question/bank/difficulty_level_column.php
classes/question/bank/practice_column.php
classes/question/bank/question_bank_filter.php
classes/question/bank/studentquiz_bank_view.php
classes/question/bank/tag_column.php
locallib.php
renderer.php

fixes #195 
@timhunt @HuongNV13 Anyone likes to have a quick review here?

there is no need to limit the results by question category if we limit the subresult already by question id

---

attempt.php
preview.php

Steps to replicate:
1. Start a Quiz or Preview a question (Ex: True/False)
2. Double click on the Check button
3. Observe the result

An error appears when double click on the Check button

---

classes/observer.php

- Do not execute this event if we change from No digest to Daily/Weekly. This will fix: Undefined variable: timetosend
- Use the correct format for strtotime function. This will fix: Notice: A non well formed numeric value encountered
Thanks,

Fix debug code related to Digest setting

---

renderer.php

Fixes the skip link text containing "<span>"

Fixes #292

---

classes/question/bank/attempts_column.php

Sorting by 'Latest' My Attempts link throws database exception

---

backup/moodle2/backup_studentquiz_stepslib.php
backup/moodle2/restore_studentquiz_stepslib.php
classes/privacy/provider.php
lang/en/studentquiz.php
tests/privacy_test.php

Hi Tim, 
I have implemented backup & restore which I  was missing for the new Pinned column.  Could you please help me to review it?
Thanks

Studentquiz: backup/restore and privacy api for pin question

---

classes/utils.php

Hi Tim, 
I have added the order clause for timecreated field.
Could you please help me to review it?
Thanks

Studentquiz: Sort by time in State history

---

classes/privacy/provider.php
classes/utils.php
db/upgrade.php
tests/privacy_test.php

Hi @timhunt, 
As your review in the PR:  https://github.com/studentquiz/moodle-mod_studentquiz/pull/346
I have improved:
1. delete_data_for_user in the privacy. I have changed the user id to guest id for the question with state new because the owner of the question is the quest. With another state such approved, disapproved, changed, hide, show. I have changed the user id to admin id.
2. In the fix_all_missing_question_state_history_after_restore function, I have used the get_recordset instead of get_records to improve performance.
3. In the upgrade.php. I have changed get_recordset to get_records and added a progress_bar.
Could you please help me to review it?
Thanks

Studentquiz: Fix code review in ticket add state history table

---

README.md

You should probably get rid of Travis CI and old repository references in README.md.
Also, indicate compatibility with Moodle >= 3.8 in the badge, as in the text further down.

Changes after code base switch.

---

classes/access/context_override.php
classes/observer.php
tests/permissions_test.php

This continues the work started in pull #379. See the discussion there.

Fix the roles sychronisation logic (again!)

---

.github/workflows/moodle-plugin-ci.yml
classes/utils.php

This seems to be the only chagne required for StudentQuiz to work with PHP8.

Fix PHP8-compatibility

---

classes/question/bank/studentquiz_bank_view.php
renderer.php
tests/bank_view_test.php
view.php

Hi Tim,
I have remove init_question_table_wanted_columns function and override the wanted_columns(remove the question text column) function just as we discussed.
Could you please help me to peer-review it.
Many thanks.

Hide question text in the question wanted columns.

---

classes/question/bank/studentquiz_bank_view.php
tests/behat/filter.feature

Hi Tim,
This PR is fixed the warning error when we are not using the filter.
Could you please help me to peer-review?
Many thanks

Fix warning message when using filter without creation time

---

classes/commentarea/comment.php
classes/commentarea/container.php
classes/utils.php
reportcomment.php
tests/behat/comment_area_create.feature
tests/utils_test.php

Hi Tim,
I have fixed two bugs in two separate commits.
Could you please help me to peer-review it.
Many thanks.

Fix throw error message when report the comment and error when report on private comment

---

classes/utils.php
lang/en/studentquiz.php
renderer.php
view.php
viewlib.php

Hi Tim,
Could you please help me to peer-review the changes?
Since this is not standard Moodle form, I use the client validation from HTML input type number.
I also create a page size const for StudentQuiz so we can reuse it everywhere in SQ.

StudentQuiz: validate pagesize input

---

renderer.php
tests/bank_view_test.php
tests/behat/pagination.feature

Show question version column in the StudentQuiz table.

Show question version in the question pool table

---

mod_form.php
tests/behat/add_studentquiz.feature

Hi @timhunt 
I have created a behat test for this case.
Because we can't identify those three select elements since they are basically the same, I need to use XPath for this case.

StudentQuiz: Add module form validation rule to studentQuiz form

---

README.md

Front page still states PHP 7.2 - 7.4 in its pill.

Stating PHP 7.3 - 8.0 on the README.md front page.

---

.github/workflows/moodle-plugin-ci.yml
classes/local/studentquiz_helper.php
classes/local/studentquiz_question.php
classes/observer.php
classes/question/bank/studentquiz_bank_view.php
classes/statistics_calculator.php
classes/utils.php
db/upgrade.php
lib.php
renderer.php
tests/cron_test.php
tests/privacy_test.php
tests/utils_test.php
version.php

Hi @timhunt ,
This issue is ready for peer review.
I have added two separate commits:
1) To fix this issue, as I have discussed with you, we will change the status of the question to draft when we disapprove of a question in StudentQuiz.
2) To update the legacy data.

StudentQuiz: Deleted orphaned question is not working as expected after MDL-78025 is implemented

---

lib.php

Indent by spaces instead of by tab.

Fix whitespace

---

changestate.php

Hi @timhunt ,
I have changed the default value of the question state so we should not update the state if users haven't changed the select value.
If you want, I can write an additional javascript to disable the button if the user hasn't changed the select value but I think since this I think we shouldn't make things more complicated.

StudentQuiz: The question state automatically changes to Disapproved when no state is selected.

---

lang/en/studentquiz.php
renderer.php
tests/behat/comment_area_create.feature

Hi @timhunt , this ticket is ready for review.

Enabled anonymous on state history table.

---

lib.php

Hi @timhunt ,
I have made code changes based on your suggested approach to fix the XSS issue in StudentQuiz. Could you please review them?
Thanks.

StudentQuiz: can we mitigate the potential XSS risks? #812360
